"""empty message

Revision ID: 31708cce10cb
Revises: e8ef11a1c512
Create Date: 2025-06-08 23:08:11.136345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31708cce10cb'
down_revision = 'e8ef11a1c512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
